# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callaccount',
            name='id',
        ),
        migrations.AddField(
            model_name='callaccount',
            name='uniqueID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
