# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0003_auto_20160608_2005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='callaccount',
            unique_together=set([('CompanyName', 'uniqueID')]),
        ),
    ]
