# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0004_auto_20160608_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='callaccount',
            name='Next_FU',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 17, 16, 59, 43, 635000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
