# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 23:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0005_callaccount_next_fu'),
    ]

    operations = [
        migrations.AddField(
            model_name='callaccount',
            name='Notes',
            field=models.CharField(default=datetime.datetime(2016, 6, 17, 23, 37, 32, 319000, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
    ]
