# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-27 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0012_auto_20161225_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_organisation',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
