# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-27 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0013_auto_20161227_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_organisation', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
