# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-28 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Calling', '0020_auto_20161228_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callaccount',
            name='owner1',
        ),
        migrations.AddField(
            model_name='callaccount',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
