# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-28 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0022_remove_callaccount_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='callaccount',
            name='test',
            field=models.CharField(default=39231, max_length=100),
            preserve_default=False,
        ),
    ]
