# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-28 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0023_callaccount_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callaccount',
            name='test',
        ),
    ]
