# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-28 22:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallAccount',
            fields=[
                ('CompanyName', models.CharField(max_length=100)),
                ('ContactName', models.CharField(max_length=100)),
                ('Next_FU', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Notes_CallAccount', models.CharField(default='', max_length=10000)),
                ('uniqueID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CallAccountNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCall1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='callaccount',
            unique_together=set([('CompanyName', 'uniqueID')]),
        ),
    ]
