# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-30 00:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0002_auto_20161228_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callaccount',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
