# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-30 00:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0003_auto_20161230_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callaccount',
            name='Next_FU',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
