# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0007_auto_20170105_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='Comments',
            new_name='comments',
        ),
    ]
