# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0009_auto_20170106_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='PhoneNumber',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='PhoneNumber',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
