# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0010_auto_20170106_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonecall',
            name='id',
        ),
        migrations.AddField(
            model_name='phonecall',
            name='uniqueID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
