# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0012_auto_20170106_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='uniqueID1',
            new_name='uniqueID',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='uniqueID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
