# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0014_auto_20170106_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='uniqueID',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='uniqueID',
        ),
        migrations.RemoveField(
            model_name='phonecall',
            name='uniqueID',
        ),
        migrations.RemoveField(
            model_name='task',
            name='uniqueID',
        ),
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonecall',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
