# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-08 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0015_auto_20170106_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecall',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
