# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-10 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0017_contact_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set([]),
        ),
    ]
