# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-10 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0018_auto_20170110_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='uniqueID',
        ),
        migrations.AddField(
            model_name='lead',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
