# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-11 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0019_auto_20170110_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Calling.Contact'),
        ),
    ]
