# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-13 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0021_auto_20170113_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Calling.Contact'),
        ),
    ]
