# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-14 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0022_emailmodel_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='notes',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
