# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-14 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0023_auto_20170114_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='EmailContent',
            field=models.TextField(max_length=10000),
        ),
    ]
