# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-14 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0024_auto_20170114_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='DateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
