# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-16 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0025_auto_20170114_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmodel',
            name='completed',
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='message_id',
            field=models.CharField(default=123, max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='subject',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
