# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0027_auto_20170121_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='from_field',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='sender',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
