# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-26 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calling', '0029_auto_20170123_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='URL',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
